routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\ProveedorController;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\CategoriasController;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\TrabajadorController;
use App\Http\Controllers\BitacoraController;
use App\Http\Controllers\CompraController;
use App\Http\Controllers\VentaController;
use App\Http\Controllers\ReportesController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/main', function () {
    return view('main');
});

Route::resource('productos', ProductoController::class);
Route::resource('proveedores', ProveedorController::class);
Route::resource('clientes', ClienteController::class);
Route::resource('usuarios', UsuarioController::class);
Route::resource('categorias', CategoriasController::class);
Route::resource('trabajador', TrabajadorController::class);
Route::resource('bitacora', BitacoraController::class);
Route::resource('compras', CompraController::class);
Route::resource('ventas', VentaController::class);
Route::resource('reportes', ReportesController::class);

Route::get('comprasData', [CompraController::class, 'show']);
Route::post('comprasfind', [CompraController::class, 'find']);

Route::get('bitacoraData', [BitacoraController::class, 'show']);

Route::get('productoData', [ProductoController::class, 'show']);
Route::post('productosupdate', [ProductoController::class, 'update']);
Route::post('productosfind', [ProductoController::class, 'find']);
Route::post('productosCreate', [ProductoController::class, 'store']);
Route::post('productosDestroy', [ProductoController::class, 'destroy']);

Route::get('proveedorData', [ProveedorController::class, 'show']);
Route::post('proveedorupdate', [ProveedorController::class, 'update']);
Route::post('proveedorfind', [ProveedorController::class, 'find']);
Route::post('proveedorCreate', [ProveedorController::class, 'store']);
Route::post('proveedorDestroy', [ProveedorController::class, 'destroy']);

Route::get('clienteData', [ClienteController::class, 'show']);
Route::post('clienteupdate', [ClienteController::class, 'update']);
Route::post('clientefind', [ClienteController::class, 'find']);
Route::post('clienteCreate', [ClienteController::class, 'store']);
Route::post('clienteDestroy', [ClienteController::class, 'destroy']);

Route::get('usuariosData', [UsuarioController::class, 'show']);
Route::post('usuariosupdate', [UsuarioController::class, 'update']);
Route::post('usuariosfind', [UsuarioController::class, 'find']);
Route::post('usuariosCreate', [UsuarioController::class, 'store']);
Route::post('usuariosDestroy', [UsuarioController::class, 'destroy']);

Route::get('categoriasData', [CategoriasController::class, 'show']);
Route::post('categoriasupdate', [CategoriasController::class, 'update']);
Route::post('categoriasfind', [CategoriasController::class, 'find']);
Route::post('categoriasCreate', [CategoriasController::class, 'store']);
Route::post('categoriasDestroy', [CategoriasController::class, 'destroy']);

Route::get('trabajadorData', [TrabajadorController::class, 'show']);
Route::post('trabajadorupdate', [TrabajadorController::class, 'update']);
Route::post('trabajadorfind', [TrabajadorController::class, 'find']);
Route::post('trabajadorCreate', [TrabajadorController::class, 'store']);
Route::post('trabajadorDestroy', [TrabajadorController::class, 'destroy']);

Route::get('obtener_productos', [ProductoController::class, 'obtenerProductos'])->name('obtener_productos');
Route::get('reportes_compras', 'App\Http\Controllers\CompraController@mostrar')->name('reportes_compras');
Route::get('reportes_compras_dia', 'App\Http\Controllers\CompraController@mostrardia')->name('reportes_compras_dia');
Route::get('reportes_ventas', 'App\Http\Controllers\VentaController@mostrar')->name('reportes_ventas');;
Route::get('reportes_ventas_dia', 'App\Http\Controllers\VentaController@mostrardia')->name('reportes_ventas_dia');
Route::post('resultados_compra', 'App\Http\Controllers\CompraController@resultados_reporte')->name('resultados_compra');
Route::post('resultados_venta', 'App\Http\Controllers\VentaController@resultados_reporte')->name('resultados_venta');

Route::get('PDFproductos', [PDFController::class, 'productosPDF'])->name('PDFProductos');
Route::get('PDFProveedores', [PDFController::class, 'proveedoresPDF'])->name('PDFProveedores');
Route::get('PDFClientes', [PDFController::class, 'clientesPDF'])->name('PDFClientes');
Route::get('PDFTrabajadores', [PDFController::class, 'trabajadoresPDF'])->name('PDFTrabajadores');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Http/Controllers/ReportesController.php
<?php

namespace App\Http\Controllers;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Models\Bitacora;
use Illuminate\Support\Facades\Auth;

class ReportesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('reportes.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/reportes/compras.blade.php
@extends('main')

@section('title', 'Reporte de compras')

@section('css')

<script src="https://kit.fontawesome.com/add63969fd.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
@endsection

@section('content')

        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Reporte de compras por fecha') }}
        </h2>
        <input type="hidden" value="{{ csrf_token() }}" id="token">

<br><br>
<div class ="card">
    <div class ="card-body">
                  
                  <form action="{{ route('resultados_compra')}}" method="POST">
                    @csrf
                  <div class="row ">

                      <div class="col-12 col-md-3">
                          <span>Fecha inicial</span>
                          <div class="form-group">
                              <input class="form-control" type="date" name="fecha_ini" id="fecha_ini">
                          </div>
                      </div>
                      <div class="col-12 col-md-3">
                          <span>Fecha final</span>
                          <div class="form-group">
                              <input class="form-control" type="date" name="fecha_fin" id="fecha_fin">
                          </div>
                      </div>
                      <div class="col-12 col-md-3 text-center mt-4">
                          <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-sm">Consultar</button>
                          </div>
                      </div>
                      
                      <div class="col-12 col-md-3 text-center">
                          <span>Total de ingresos: <b> </b></span>
                          <div class="form-group">
                              <strong>usd {{$total}}</strong>
                          </div>
                      </div>
                  </div>


    <table id="compras" class="table table-hover table-striped table-bordered table-sm mt-4" style="width:100%">
  <thead>
      <tr >
          <th style="width:150px" scope="col">Numero de factura</th>
          <th scope="col">Fecha</th>
          <th scope="col">Total</th>
          <th scope="col">Proveedor</th>
          <th scope="col">Acciones</th>
      </tr>
  </thead>
  <tbody>
      @foreach($compras as $compra)
      <tr>
                <td>{{$compra->id}}</td>
                <td>{{$compra->fecha_compra}}</td>
                <td>{{$compra->total_pagar}}</td>
                <td>{{$compra->proveedor->nombre_proveedor}}</td>
                <td>
                    <a href="{{route('compras.show', $compra->id)}}" class="btn btn-light">PDF</a>
                </td>
            </tr>
      @endforeach
  </tbody>
</table>
    </div>
</div>

@endsection
@section('js')

<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>

<script>
    $(document).ready(function() {

        compras = $('#compras').DataTable({
        "language": {
            "lengthMenu": "Mostrar _MENU_ registros por paginas",
            "zeroRecords": "No se encontraron registros",
            "info": "Mostrando  _END_ registros de un total de _TOTAL_ registros",
             
            "emptyTable": "Ningún dato disponible en esta tabla",
            "infoEmpty": "No se encontraron registros",
            "search": "Buscar",
            "loadingRecords": "Cargando...",
            "processing": "Procesando...",

                "paginate": {
                "first": "Primero",
                "last": "Último",
                "next": "Siguiente",
                "previous": "Anterior"
            },
        },
    });
});

</script>
@endsection

resources/views/reportes/compras_dia.blade.php
@extends('main')

@section('title', 'Reporte de compras')

@section('css')

<script src="https://kit.fontawesome.com/add63969fd.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
@endsection

@section('content')

        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Reporte de compras por día') }}
        </h2>
        <input type="hidden" value="{{ csrf_token() }}" id="token">

<br><br>
<div class ="card">
    <div class ="card-body">

                    <div class="row ">
                        <div class="col-12 col-md-4 text-center">
                            <span>Fecha de consulta: <b> </b></span>
                            <div class="form-group">
                                <strong>{{\Carbon\Carbon::now('America/Caracas')->format('d/m/Y')}}</strong>
                            </div>
                        </div>
                        <div class="col-12 col-md-4 text-center">
                            <span>Cantidad de registros: <b></b></span>
                            <div class="form-group">
                                <strong>{{$compras->count()}}</strong>
                            </div>
                        </div>
                        <div class="col-12 col-md-4 text-center">
                            <span>Total de ingresos: <b> </b></span>
                            <div class="form-group">
                                <strong>usd {{$total}}</strong>
                            </div>
                        </div>
                    </div>


    <table id="compras" class="table table-hover table-striped table-bordered table-sm mt-4" style="width:100%">
  <thead>
      <tr >
          <th style="width:150px" scope="col">Numero de factura</th>
          <th scope="col">Fecha</th>
          <th scope="col">Total</th>
          <th scope="col">Proveedor</th>
          <th scope="col">Acciones</th>
      </tr>
  </thead>
  <tbody>
      @foreach($compras as $compra)
      <tr>
                <td>{{$compra->id}}</td>
                <td>{{$compra->fecha_compra}}</td>
                <td>{{$compra->total_pagar}}</td>
                <td>{{$compra->proveedor->nombre_proveedor}}</td>
                <td>
                    <a href="{{route('compras.show', $compra->id)}}" class="btn btn-light">PDF</a>
                </td>
            </tr>
      @endforeach
  </tbody>
</table>
    </div>
</div>

@endsection
@section('js')

<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>

<script>
    $(document).ready(function() {

        compras = $('#compras').DataTable({
        "language": {
            "lengthMenu": "Mostrar _MENU_ registros por paginas",
            "zeroRecords": "No se encontraron registros",
            "info": "Mostrando  _END_ registros de un total de _TOTAL_ registros",
             
            "emptyTable": "Ningún dato disponible en esta tabla",
            "infoEmpty": "No se encontraron registros",
            "search": "Buscar",
            "loadingRecords": "Cargando...",
            "processing": "Procesando...",

                "paginate": {
                "first": "Primero",
                "last": "Último",
                "next": "Siguiente",
                "previous": "Anterior"
            },
        },
    });
});

</script>
@endsection

resources/views/reportes/index.blade.php
@extends('main')

@section('title', 'Reportes')

@section('css')

<script src="https://kit.fontawesome.com/add63969fd.js" crossorigin="anonymous"></script>
@endsection

@section('content')

<div class="row row-cols-1 row-cols-md-2 g-4">
  <div class="col">
    <div class="card">
      <img src="compras.jpeg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Reportes de compras por fecha</h5>
        <p class="card-text">Acá podrá ver las compras en un rango de fecha</p>
        <a href="reportes_compras" class="btn btn-primary">Ir a reportes</a>  
    </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="compras_dia.jpeg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Reportes de compras por día</h5>
        <p class="card-text">Acá podrá ver las compras registradas el día de hoy</p>
        <a href="reportes_compras_dia" class="btn btn-primary">Ir a reportes</a>  
    </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="ventas.jpeg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Reportes de venta por fecha</h5>
        <p class="card-text">Acá podrá ver las ventas en un rango de fecha</p>
        <a href="reportes_ventas" class="btn btn-primary">Ir a reportes</a>  
    </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="ventas_dia.jpeg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Reportes de venta por día</h5>
        <p class="card-text">Acá podrá ver las ventas registradas el día de hoy</p>
        <a href="reportes_ventas_dia" class="btn btn-primary">Ir a reportes</a>  
    </div>
    </div>
  </div>
</div>

@endsection
@section('js')


@endsection

resources/views/reportes/ventas.blade.php
@extends('main')

@section('title', 'Reporte de ventas')

@section('css')

<script src="https://kit.fontawesome.com/add63969fd.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
@endsection

@section('content')

        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Reporte de ventas por fecha') }}
        </h2>
        <input type="hidden" value="{{ csrf_token() }}" id="token">

<br><br>
<div class ="card">
    <div class ="card-body">

              <form action="{{ route('resultados_venta')}}" method="POST">
                @csrf
              <div class="row ">

                  <div class="col-12 col-md-3">
                      <span>Fecha inicial</span>
                      <div class="form-group">
                          <input class="form-control" type="date" 
                          value="{{old('fecha_ini')}}" 
                          name="fecha_ini" id="fecha_ini">
                      </div>
                  </div>
                  <div class="col-12 col-md-3">
                      <span>Fecha final</span>
                      <div class="form-group">
                          <input class="form-control" type="date" 
                          value="{{old('fecha_fin')}}" 
                          name="fecha_fin" id="fecha_fin">
                      </div>
                  </div>
                  <div class="col-12 col-md-3 text-center mt-4">
                      <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-sm">Consultar</button>
                      </div>
                  </div>
                  
                  <div class="col-12 col-md-3 text-center">
                      <span>Total de ingresos: <b> </b></span>
                      <div class="form-group">
                          <strong>USD {{$total}}</strong>
                      </div>
                  </div>
              </div>
              </form>


        <table id="proveedores" class="table table-hover table-striped table-bordered table-sm mt-4" style="width:100%">
                        <thead >
                            <tr >
                                <th style="width:50px" scope="col">Número de factura</th>
                                <th style="width:100px" scope="col">Cliente</th>
                                <th style="width:100px" scope="col">Fecha</th>
                                <th style="width:100px" scope="col">Total</th>
                                <th style="width:100px" scope="col">Trabajador</th>
                                <th style="width:100px" scope="col">Acciones</th>
                            </tr>
                        </thead>
                    <tbody>
                    @foreach($ventas as $venta)
                <tr>
                <td>{{$venta->id}}</td>
                <td>{{$venta->cliente->nombre_cliente}}</td>
                <td>{{$venta->fecha_venta}}</td>
                <td>{{$venta->total_pagar}}</td>
                <td>{{$venta->trabajadors->nombre_trabajador}}</td>
                <td>
                    <a href="{{route('ventas.show', $venta->id)}}" class="btn btn-light">PDF</a>
                </td>
            </tr>
                    @endforeach
                </tbody>
            </table>
    </div>
</div>
@endsection
@section('js')

<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>

<script>
    $(document).ready(function() {

        proveedores = $('#proveedores').DataTable({
        "language": {
            "lengthMenu": "Mostrar _MENU_ registros por paginas",
            "zeroRecords": "No se encontraron registros",
            "info": "Mostrando  _END_ registros de un total de _TOTAL_ registros",
             
            "emptyTable": "Ningún dato disponible en esta tabla",
            "infoEmpty": "No se encontraron registros",
            "search": "Buscar",
            "loadingRecords": "Cargando...",
            "processing": "Procesando...",

                "paginate": {
                "first": "Primero",
                "last": "Último",
                "next": "Siguiente",
                "previous": "Anterior"
            },
        },
    });




});
</script>

@endsection

resources/views/reportes/ventas_dia.blade.php
@extends('main')

@section('title', 'Ventas')

@section('css')

<script src="https://kit.fontawesome.com/add63969fd.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
@endsection

@section('content')

        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Reporte de ventas por día') }}
        </h2>
        <input type="hidden" value="{{ csrf_token() }}" id="token">

<br><br>
<div class ="card">
    <div class ="card-body">

                     <div class="row ">
                        <div class="col-12 col-md-4 text-center">
                            <span>Fecha de consulta: <b> </b></span>
                            <div class="form-group">
                                <strong>{{\Carbon\Carbon::now('America/Caracas')->format('d/m/Y')}}</strong>
                            </div>
                        </div>
                        <div class="col-12 col-md-4 text-center">
                            <span>Cantidad de registros: <b></b></span>
                            <div class="form-group">
                                <strong>{{$ventas->count()}}</strong>
                            </div>
                        </div>
                        <div class="col-12 col-md-4 text-center">
                            <span>Total de ingresos: <b> </b></span>
                            <div class="form-group">
                                <strong>usd {{$total}}</strong>
                            </div>
                        </div>
                    </div>

                    


        <table id="proveedores" class="table table-hover table-striped table-bordered table-sm mt-4" style="width:100%">
                        <thead >
                            <tr >
                                <th style="width:50px" scope="col">Número de factura</th>
                                <th style="width:100px" scope="col">Cliente</th>
                                <th style="width:100px" scope="col">Fecha</th>
                                <th style="width:100px" scope="col">Total</th>
                                <th style="width:100px" scope="col">Trabajador</th>
                                <th style="width:100px" scope="col">Acciones</th>
                            </tr>
                        </thead>
                    <tbody>
                    @foreach($ventas as $venta)
                <tr>
                <td>{{$venta->id}}</td>
                <td>{{$venta->nombre_cliente}}</td>
                <td>{{$venta->fecha_venta}}</td>
                <td>{{$venta->total_pagar}}</td>
                <td>{{$venta->nombre_trabajador}}</td>
                <td>
                    <a href="{{route('ventas.show', $venta->id)}}" class="btn btn-light">PDF</a>
                </td>
            </tr>
                    @endforeach
                </tbody>
            </table>
    </div>
</div>
@endsection
@section('js')

<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>

<script>
    $(document).ready(function() {

        proveedores = $('#proveedores').DataTable({
        "language": {
            "lengthMenu": "Mostrar _MENU_ registros por paginas",
            "zeroRecords": "No se encontraron registros",
            "info": "Mostrando  _END_ registros de un total de _TOTAL_ registros",
             
            "emptyTable": "Ningún dato disponible en esta tabla",
            "infoEmpty": "No se encontraron registros",
            "search": "Buscar",
            "loadingRecords": "Cargando...",
            "processing": "Procesando...",

                "paginate": {
                "first": "Primero",
                "last": "Último",
                "next": "Siguiente",
                "previous": "Anterior"
            },
        },
    });




});
</script>

@endsection